#pragma config(Sensor, port2,  touch1,         sensorVexIQ_LED)
#pragma config(Motor,  motor8,           ,             tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*    Module:     BT_Demo.c                                                    */
/*    Author:     Simon Burfield : Heavily based on BT_demo by James Pearman   */
/*    Created:    30 Mar 2016                                                  */
/*                                                                             */
/*                                                                             */
/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*    The author is supplying this software for use with the VEX IQ            */
/*    control system. This file can be freely distributed and teams are        */
/*    authorized to freely use this program , however, it is requested that    */
/*    improvements or additions be shared with the Vex community via the vex   */
/*    forum.  Please acknowledge the work of the authors when appropriate.     */
/*    Thanks.                                                                  */
/*                                                                             */
/*    Licensed under the Apache License, Version 2.0 (the "License");          */
/*    you may not use this file except in compliance with the License.         */
/*    You may obtain a copy of the License at                                  */
/*                                                                             */
/*      http://www.apache.org/licenses/LICENSE-2.0                             */
/*                                                                             */
/*    Unless required by applicable law or agreed to in writing, software      */
/*    distributed under the License is distributed on an "AS IS" BASIS,        */
/*    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. */
/*    See the License for the specific language governing permissions and      */
/*    limitations under the License.                                           */
/*                                                                             */
/*-----------------------------------------------------------------------------*/

// Check platform
#ifndef VexIQ
#error "This program is designed for the VexIQ platform"
#else

// Check if Smart Radio features are enabled
#ifndef VexIQ_SR
#error "This sample needs to have the smart radio features enabled"
#else

/*-----------------------------------------------------------------------------*/
/*  Discover devices and look for a touch sensor                               */
/*-----------------------------------------------------------------------------*/
/*
void
iqDiscoverDevices()
{
TVexIQDeviceTypes   type;
TDeviceStatus       status;
short               ver;
short               index;

// Get all device info
for(index=(short)PORT1;index<=(short)PORT12;index++) {
getVexIqDeviceInfo( index, type, status, ver );

// Touch LED on any port used to start stop robot
if( type == vexIQ_SensorLED )
robotTouchSensor = (tSensors)index;
}
}
8?
/*-----------------------------------------------------------------------------*/
/*  Setup message to remote device if touch LED state changed                  */
/*-----------------------------------------------------------------------------*/
void checkTouchSensor()
{
	static  int   oldValue = -1;
	static  char  msg[41];

	// If Touch LED installed
	if(touch1)
	{
		int value = SensorValue[ touch1 ];

		// see if value has changed
		if(  value != oldValue )
		{
			msg[0] = 't'; // t for touch
			msg[1] = value;

			displayString(2,"but %d", value );

			// remember old value
			oldValue = value;

			// User message to remote device
			sendUserMessage(msg);
		}
	}
}

/*-----------------------------------------------------------------------------*/
/*  Check if we received a user message from the bluetooth device              */
/*-----------------------------------------------------------------------------*/
void checkForUserMessage()
{
	char usrMsg[41]; //extra byte for null chvalue

	if(userMessageAvailable())
	{
		// Get the incomming message
		readUserMessage(usrMsg);

		displayString(1, usrMsg );

		// l means led :  m means motor
		if( usrMsg[0] == 'l' )
		{
			switch( usrMsg[1] )
			{
				case  '1':  setTouchLEDColor( touch1, colorBlue );   displayString(1, "Blue  " ); break;
				case  '2':  setTouchLEDColor( touch1, colorRed );    displayString(1, "Red   " );break;
				case  '3':  setTouchLEDColor( touch1, colorGreen );  displayString(1, "Green " );break;
				case  '4':  setTouchLEDColor( touch1, colorOrange ); displayString(1, "Orange" );break;
				default:  setTouchLEDColor( touch1, colorNone );   displayString(1, "      " );break;
			}
		}
		else if (usrMsg[0] == 'm')
		{

			switch( usrMsg[1] )
			{
				case  '1':
					setMotorSpeed(motor8,100);
					displayString(3, usrMsg );
					break;
				case 	'2':
					setMotorSpeed(motor8,-100);
					break;
				default :
					setMotorSpeed(motor8,0);
					break;
			}
		}
	}
}

/*-----------------------------------------------------------------------------*/
task main()
{
	eraseDisplay();

	// run forever looking for user messages
	while(true){

		checkForUserMessage();
		checkTouchSensor();

		wait1Msec(10);
	}
}

#endif // End Smart Radio features enabled check
#endif // End platform check
